if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.config/X11/xresources ]] && xrdb -load ~/.config/X11/xresources

internal_display=LVDS-1
external_display=HDMI-2
if xrandr | grep "$external_display connected"; then
    xrandr \
        --output "$internal_display" --mode 1366x768 --pos 0x0 \
        --output "$external_display" --primary --mode 1920x1080 --pos 1366x0
fi

exec i3
